import {createGame,act,reason,nextShift,consumption,seats,findPassenger,occupiedRoom,CONDITIONS,TYPES,DEFAULTS,validSave} from './engine.mjs?v=astra-1';
import {portrait,roomArt,orbit} from './art.mjs?v=astra-1';
const KEY='transfer-astra-v1';let state,selected=null,storage=true,flightPage=0;
try{const saved=JSON.parse(localStorage.getItem(KEY));state=validSave(saved)?saved:createGame();}catch{state=createGame();storage=false;}
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const icon={dry:'◈',water:'≋'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,attrs='',disabled=false,cls='')=>`<button class="${cls}" data-action="${action}" ${attrs} ${disabled?'disabled':''}>${text}</button>`;
function reveal(selector){}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storage=false;}}
let toastTimer;function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3600);}
function status(p){return p.flight?'Ожидает рейс':!p.talked?'Нужен разговор':p.condition&&!p.fulfilled?'Есть условие':'Готов к назначению';}
function render(){
 if(selected&&!findPassenger(state,selected))selected=null;
 const s=state,cost=consumption(s),p=findPassenger(s,selected),remaining=s.config.ticks-s.tick;
 app.innerHTML=`<header class="topbar"><a class="brand" href="#" aria-label="Пересадочная станция"><span class="brand-mark">╋</span> ОРБИТАЛЬНАЯ СЛУЖБА <span class="brand-divider">/</span> ТЕРМИНАЛ 07</a><nav aria-label="Сервис">${button('Регламент','help')}${button('Параметры','settings')}${button('↻','restart','aria-label="Начать заново" title="Начать заново"')}</nav></header>
 <main><section class="hero">${orbit}<div class="hero-copy"><div class="eyebrow"><span class="dot"></span> ВНЕШНЕЕ КОЛЬЦО · СЕКТОР 04</div><h1>Пересадочная<br><em>станция</em><span class="title-period">.</span></h1><p>У каждого свой путь. У вас — тридцать тактов.</p></div><div class="hero-stamp">ПУНКТ ТРАНЗИТА<br><strong>07 / ASTRA</strong><span>ДИСПЕТЧЕРСКИЙ ТЕРМИНАЛ</span></div></section>
 <section class="shiftbar" aria-label="Состояние смены"><div class="shift-id"><span class="eyebrow">ТЕКУЩАЯ СМЕНА</span><strong>${String(s.shift).padStart(2,'0')}</strong><span class="live-label">${s.failed?'ПРИОСТАНОВЛЕНА':s.ended?'ЗАВЕРШЕНА':'НА СВЯЗИ'}</span></div><div class="meter time-meter"><div><span>Время смены</span><strong>${String(s.tick).padStart(2,'0')} <small>/ ${s.config.ticks}</small></strong></div><div class="tick-track">${Array.from({length:s.config.ticks},(_,i)=>`<i class="${i<s.tick?'used':''}"></i>`).join('')}</div></div><div class="meter ${s.resource<8?'critical':''}"><div><span>Ресурс станции</span><strong>${s.resource} <small>/ ${s.config.resource}</small></strong></div><div class="resource-track"><i style="width:${s.resource/s.config.resource*100}%"></i></div><small>${cost?`Расход ${cost} ед./такт · хватит на ${Math.ceil(s.resource/cost)} такт.`:'Система в режиме ожидания'}</small></div><div class="advance">${button('Пропустить такт <span>+1 →</span>','wait','',s.ended||s.failed,'primary')}<small>Время идёт только по вашей команде</small></div></section>
 ${s.failed?`<section class="notice danger"><div><strong>Ресурс исчерпан</strong><p>Терминал приостановлен. Пассажиры остаются в комнатах. Попробуйте сократить ожидание рейсов.</p></div>${button('Новая попытка','restart','','','primary')}</section>`:s.ended?`<section class="notice"><div><strong>Смена ${s.shift} завершена</strong><p>Доставлено: ${s.stats.departed}. Ушли из очереди: ${s.stats.left}. В следующей смене ресурс восстановится; пассажиры и бронирования сохранятся.</p></div>${button('Открыть смену '+(s.shift+1),'next','','','primary')}</section>`:''}
 <section class="workspace"><aside class="panel queue-panel"><div class="section-head"><div><span class="eyebrow">01 / ПРИБЫТИЕ</span><h2>Зал ожидания <span class="counter">${s.queue.length}</span></h2></div><span class="status-light"></span></div><p class="panel-caption">Примите пассажира до конца ожидания.</p><div class="queue-list">${s.queue.map(q=>`<button class="passenger ${selected===q.id?'selected':''}" data-action="select" data-id="${q.id}" aria-pressed="${selected===q.id}"><div class="passenger-top">${portrait(q)}<div><strong>${esc(q.name)}</strong><span>${esc(q.race)}</span></div><span class="patience ${q.patience<=3?'urgent':''}">${q.patience}<small>такт.</small></span></div><div class="passenger-route"><span>↗ ${q.dest==='Сигма-4'?'Сектор Сигма':q.dest==='Альфа-9'?'Сектор Альфа':'Марсианский сектор'}</span><span>${icon[q.type]} ${TYPES[q.type]}</span></div><div class="patience-track"><i style="width:${q.patience/(s.config.patience+2)*100}%"></i></div></button>`).join('')||'<div class="empty-queue">Новых пассажиров пока нет.<br><small>Следующее прибытие через '+(s.config.arrivalEvery-s.time%s.config.arrivalEvery)+' такт.</small></div>'}</div><div class="queue-footer"><span>ПРИБЫТИЕ КАЖДЫЕ ${s.config.arrivalEvery} ТАКТА</span><span>↙</span></div></aside>
 <section class="rooms-panel"><div class="section-head"><div><span class="eyebrow">02 / РАЗМЕЩЕНИЕ</span><h2>Жилой модуль</h2></div><span class="occupancy">${s.rooms.filter(r=>r.p).length}<small> / ${s.rooms.length} ЗАНЯТО</small></span></div><div class="rooms">${s.rooms.map(r=>roomView(r)).join('')}</div></section>
 <aside class="panel flights-panel"><div class="section-head"><div><span class="eyebrow">03 / ОТПРАВЛЕНИЕ</span><h2>Табло рейсов</h2></div><span class="departure-icon">↗</span></div><p class="panel-caption">Посадка автоматическая. Не опаздывайте.</p><div class="flight-list">${s.flights.slice(flightPage*3,flightPage*3+3).map((f,i)=>flightView(f,p,i)).join('')}</div><div class="flight-pages">${button('←','flights-prev','aria-label="Предыдущие рейсы"',flightPage===0)}<span>${flightPage===0?'Ближайшие рейсы':'Следующие рейсы'}</span>${button('→','flights-next','aria-label="Следующие рейсы"',flightPage===1)}</div><div class="dispatcher-note"><span class="eyebrow">ПАМЯТКА ДИСПЕТЧЕРУ</span><p>Пассажир с бронью занимает комнату до вылета. Учитывайте время ожидания и запас ресурса.</p><span>Рейсы уходят даже пустыми.</span></div></aside></section>
 <section class="action-panel" aria-label="Действия пассажира">${actionView(p)}</section>
 <footer class="station-footer"><div><span class="eyebrow">ЖУРНАЛ СТАНЦИИ</span><span class="log-text">${s.log[0]?`[${String(s.log[0].at).padStart(2,'0')}] ${esc(s.log[0].text)}`:''}</span>${button('Весь журнал ↗','log')}</div><span>ВЫЛЕТЕЛИ <b>${s.stats.departed}</b> <i>·</i> УШЛИ <b>${s.stats.left}</b></span></footer><div class="page-foot"><span>ASTRA / ПРОТОТИП 01</span><span>${storage?'Состояние сохраняется автоматически':'Сохранение недоступно в этом браузере'}</span><span>ПЕРЕСАДОЧНАЯ СТАНЦИЯ</span></div></main>`;
}
function roomView(r){const p=r.p,f=p?.flight?state.flights.find(f=>f.id===p.flight):null;return `<article class="room ${r.type} ${p?'occupied':''} ${selected===p?.id?'selected':''}"><div class="room-heading"><span><b>${String(r.id+1).padStart(2,'0')}</b> ${icon[r.type]} ${TYPES[r.type]} комната</span><span class="room-state ${r.prepared?'ready':''}">${p?'ЗАНЯТА':r.prepared?'ПОДГОТОВЛЕНА':'НЕ ПОДГОТОВЛЕНА'}</span></div><div class="room-scene">${roomArt(r)}<span class="room-code">${r.type==='water'?'HYDRO':'HABITAT'} / ${String(r.id+1).padStart(2,'0')}</span><span class="scene-label">${p?esc(p.name):r.prepared?'Готова к заселению':'Ожидает подготовки'}</span></div><div class="room-bottom">${p?`<div><strong>${esc(p.name)} <span class="room-consumption">−${p.count} ед./такт</span></strong><small>${f?`${f.dest} · вылет через ${f.at-state.time} такт.`:status(p)}</small></div>${button(p.flight?'Бронь ↗':'Выбрать →','select',`data-id="${p.id}" aria-pressed="${selected===p.id}"`,'','subtle')}`:`<div><strong>${r.prepared?'Свободна':'Подготовьте отсек'}</strong><small>${r.prepared?'Расход ресурса: 0':'Подготовка не тратит такт'}</small></div>${button(r.prepared?'Готово ✓':'Подготовить','prepare',`data-room="${r.id}"`,r.prepared||state.ended||state.failed,'subtle')}`}</div></article>`;}
function flightView(f,p,i){const free=f.capacity-f.used,blocked=reason(state,'assign',p?.id,f.id),show=!!p&&!!occupiedRoom(state,p.id)&&!p.flight;return `<article class="flight ${i===0?'soon':''} ${p?.flight===f.id?'booked':''}"><div class="flight-top"><span class="flight-number">TR–${f.id.slice(1).padStart(3,'0')}</span><span class="flight-time">${f.at-state.time} <small>такт.</small></span></div><h3>${f.dest}<span>↗</span></h3><div class="flight-capacity"><span class="seats">${Array.from({length:f.capacity},(_,i)=>`<i class="seat ${i<f.used?'filled':''}"></i>`).join('')}</span><span>${f.used} / ${f.capacity} мест</span></div>${show?`${button('Назначить · 1 такт','assign',`data-id="${p.id}" data-flight="${f.id}" title="${esc(blocked||'Забронировать '+seats(p)+' мест')}"`,!!blocked,'flight-assign')}<small class="blocked-reason">${blocked||`Свободно ${free} · требуется ${seats(p)}`}</small>`:p?.flight===f.id?'<span class="booking-label">✓ Бронь подтверждена</span>':''}</article>`;}
function actionView(p){if(!p)return `<div class="action-empty"><div class="action-symbol">⌘</div><div><span class="eyebrow">ПУЛЬТ ДИСПЕТЧЕРА</span><h2>Каждая пересадка начинается с решения</h2><p>Подготовьте комнату, затем выберите пассажира в очереди.</p></div><div class="loop-hint">Приём <span>→</span> Разговор <span>→</span> Условие <span>→</span> Рейс</div></div>`;
 const inQueue=state.queue.includes(p),r=occupiedRoom(state,p.id),f=state.flights.find(f=>f.id===p.flight),condition=p.condition&&CONDITIONS[p.condition];let content;
 if(inQueue){const b=reason(state,'accept',p.id);content=`<p>Нужна ${TYPES[p.type].toLowerCase()} комната. Полное направление и условия откроются после разговора.</p>${button('Принять пассажира <span>1 такт →</span>','accept',`data-id="${p.id}"`,!!b,'primary')}<small class="action-reason">${b||'Приём займёт 1 такт и запустит расход ресурса.'}</small>`;}
 else if(p.flight)content=`<p class="confirmed">✓ ${f?.dest} · рейс TR–${f?.id.slice(1).padStart(3,'0')} · ${seats(p)} мест</p><p>Автоматический вылет через <strong>${f?.at-state.time} такт.</strong> Комната освободится после отправления.</p><span class="quiet-label">Дополнительные действия не нужны</span>`;
 else if(!p.talked)content=`<p>Пассажир размещён. Уточните направление и особые условия перед бронированием.</p>${button('Поговорить <span>0 тактов →</span>','talk',`data-id="${p.id}"`,state.ended||state.failed,'primary')}`;
 else if(condition&&!p.fulfilled)content=`<p><strong>${condition.name}.</strong> ${condition.text}</p><div class="condition-actions">${button(condition.action+' · 0 тактов','fulfill',`data-id="${p.id}"`,state.ended||state.failed,'primary')}${p.condition==='contraband'?button('Допустить без оплаты','fulfill',`data-id="${p.id}" data-extra="allow"`,state.ended||state.failed):''}</div>`;
 else content=`<p class="confirmed">✓ ${condition?'Условие выполнено':'Особых условий нет'}. Нужно мест: ${seats(p)}.</p><p>Выберите рейс <strong>${p.dest}</strong> на табло справа. Назначение стоит 1 такт; вылет — по расписанию.</p>`;
 return `<div class="selected-person">${portrait(p,70)}<div><span class="eyebrow">${inQueue?'В ОЧЕРЕДИ':`КОМНАТА ${String(r.id+1).padStart(2,'0')}`}</span><h2>${esc(p.name)}</h2><span>${p.race} · ${p.talked?p.dest:'Направление не уточнено'}</span></div></div><div class="action-body"><div class="steps">${['Приём','Разговор','Условие','Рейс'].map((n,i)=>`<span class="${[!inQueue,p.talked,p.talked&&(!p.condition||p.fulfilled),!!p.flight][i]?'done':''}">${i+1} ${n}</span>`).join('')}</div>${content}</div>`;
}
function open(content){modal.innerHTML=`<div class="modal-top"><span class="eyebrow">ТЕРМИНАЛ 07 / СЛУЖЕБНОЕ ОКНО</span>${button('×','close','aria-label="Закрыть"')}</div>${content}`;modal.showModal();}
function help(){open(`<h2>Регламент терминала</h2><p>Проведите как можно больше пассажиров через станцию за ${state.config.ticks} тактов, сохранив ресурс.</p><ol><li>Подготовьте подходящую комнату — бесплатно.</li><li>Выберите пассажира и примите его — <b>1 такт</b>.</li><li>Поговорите, затем выполните условие — бесплатно.</li><li>Выберите подходящий рейс — <b>1 такт</b>.</li><li>Бронь готова. В момент отправления пассажир улетит автоматически.</li></ol><h3>Время и ресурс</h3><p>Реальное время не влияет на игру. «Пропустить такт» вручную продвигает время на один шаг. Ожидание пассажиров и автоматический вылет не добавляют отдельных тактов.</p><p>Каждый человек в комнате тратит 1 ресурс за такт, включая такт приёма и такт вылета. Питомец и груз занимают место на рейсе, но не расходуют ресурс. Группа из двух человек тратит 2 ресурса.</p><h3>Уточнения прототипа</h3><p>ТЗ не задаёт цену подготовки и выполнения условий: здесь они бесплатны. После вылета комнату нужно подготовить снова. Рейс можно забронировать за один такт до вылета.</p><p>При нулевом ресурсе до конца смены попытка приостанавливается: начните заново. После полного завершения смены можно открыть следующую: ресурс восстановится, очередь, пассажиры и брони сохранятся. Расписание продолжается.</p><p>Новые пассажиры приходят каждые ${state.config.arrivalEvery} такта; сценарий повторяемый. До разговора особые условия скрыты. Экономики, репутации и прокачки нет.</p>`);}
function settings(){open(`<h2>Параметры прототипа</h2><p>Изменения запустят новую игру. Текущая смена будет заменена.</p><form id="settings"><label>Тактoв в смене<input name="ticks" type="number" min="10" max="60" value="${state.config.ticks}" required></label><label>Начальный ресурс<input name="resource" type="number" min="10" max="150" value="${state.config.resource}" required></label><label>Сухих комнат<input name="dry" type="number" min="0" max="5" value="${state.config.rooms.filter(r=>r==='dry').length}" required></label><label>Водных комнат<input name="water" type="number" min="0" max="5" value="${state.config.rooms.filter(r=>r==='water').length}" required></label><label>Прибытие каждые N тактов<input name="arrivalEvery" type="number" min="1" max="8" value="${state.config.arrivalEvery}" required></label><label>Базовое ожидание в очереди<input name="patience" type="number" min="3" max="20" value="${state.config.patience}" required></label><button class="primary" type="submit">Применить и начать заново</button>${button('Вернуть параметры ТЗ','defaults','type="button"')}</form>`);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;if(a==='flights-prev'||a==='flights-next'){flightPage=a==='flights-next'?1:0;render();return;}if(a==='select'){selected=id;render();reveal('.action-panel');return;}if(a==='close'){modal.close();return;}if(a==='help'){help();return;}if(a==='settings'){settings();return;}if(a==='log'){open(`<h2>Журнал станции</h2><div class="full-log">${state.log.map(l=>`<p><span>С${l.shift} / ${String(l.at).padStart(2,'0')}</span> ${esc(l.text)}</p>`).join('')}</div>`);return;}
 if(a==='restart'){open(`<h2>Начать заново?</h2><p>Текущая смена и её результат будут сброшены. Параметры сохранятся.</p><div class="condition-actions">${button('Начать новую игру','confirm-restart','','','primary')}${button('Продолжить смену','close')}</div>`);return;}
 if(a==='confirm-restart'||a==='defaults'){state=createGame(a==='defaults'?DEFAULTS:state.config);selected=null;modal.close();save();render();return;}
 if(a==='next'){nextShift(state);save();render();return;}
 const before=state.stats.departed;const result=act(state,a,a==='prepare'?Number(b.dataset.room):id,b.dataset.flight||b.dataset.extra);if(!result.ok)toast(result.message);else{if(a==='accept')selected=id;save();render();if(a==='accept'||a==='assign')reveal('.action-panel');if(a==='talk'||a==='fulfill'){const passenger=findPassenger(state,id);if(passenger&&(!passenger.condition||passenger.fulfilled))reveal('.flights-panel');}if(state.stats.departed>before)toast(`Рейс отправлен. Пассажиров: ${state.stats.departed-before}.`);}
});
document.addEventListener('submit',e=>{if(e.target.id!=='settings')return;e.preventDefault();const d=new FormData(e.target),o=Object.fromEntries([...d].map(([k,v])=>[k,Number(v)]));if(!o.dry&&!o.water){toast('Нужна хотя бы одна комната.');return;}state=createGame({...o,rooms:[...Array(o.dry).fill('dry'),...Array(o.water).fill('water')]});selected=null;modal.close();save();render();});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
render();

