import assert from 'node:assert/strict';
import {createGame,act,restoreGame,nextShift,ECONOMY} from './engine.mjs';
let tests=0;const test=(name,fn)=>{fn();tests++;console.log('PASS '+name);};
function departure(condition,decision,config={},seed=98173){const s=createGame(config);s.rng=seed;s.time=4;s.tick=4;s.queue=[];s.rooms[0].p={id:'test',name:'Test',condition,decision,count:condition==='group'?2:1,flight:'F5'};act(s,'wait');return s;}
test('Defaults and charged preparation, repeat and insufficient-resource no-ops',()=>{const s=createGame();assert.equal(s.credits,0);assert.equal(s.config.prepareCost,2);assert.equal(s.config.refillRate,3);assert.equal(s.config.refillMax,100);act(s,'prepare',0);assert.equal(s.resource,43);assert.equal(s.tick,0);const b=JSON.stringify(s);assert(!act(s,'prepare',0).ok);assert.equal(JSON.stringify(s),b);s.resource=1;const c=JSON.stringify(s);assert(!act(s,'prepare',1).ok);assert.equal(JSON.stringify(s),c);});
test('Successful atomic purchase consumes credits only, respects exact capacity',()=>{const s=createGame();s.resource=40;s.credits=15;const time=s.time;assert(act(s,'refill',5).ok);assert.equal(s.resource,45);assert.equal(s.credits,0);assert.equal(s.time,time);const b=JSON.stringify(s);assert(!act(s,'refill',1).ok);assert.equal(JSON.stringify(s),b);});
test('Invalid, oversized and unaffordable purchases never mutate state',()=>{for(const n of [0,-1,1.5,NaN,101,6]){const s=createGame();s.resource=40;s.credits=1000;const b=JSON.stringify(s);assert(!act(s,'refill',n).ok);assert.equal(JSON.stringify(s),b);}const s=createGame();s.resource=10;s.credits=2;assert(!act(s,'refill',1).ok);assert.equal(s.credits,2);});
test('All inclusive reward ranges and contraband penalty bounds',()=>{for(const [type,min,max,rep]of [[null,10,15,1],['pet',10,20,2],['group',15,25,3],['cargo',15,20,1],['contraband',25,35,null]]){const values=new Set();for(let i=0;i<2000;i++){const s=departure(type,'allow',{},i*47397);assert(s.credits>=min&&s.credits<=max);values.add(s.credits);if(rep===null)assert(s.reputation>=5&&s.reputation<=8);else assert.equal(s.reputation,10+rep);assert.equal(s.repEvents[0].credits,s.credits);}assert(values.has(min)&&values.has(max));}});
test('Seized contraband pays ordinary reward without penalty',()=>{const s=departure('contraband','seize');assert(s.credits>=10&&s.credits<=15);assert.equal(s.reputation,11);});
test('Acceptance, conversation, conditions and booking never pay before departure',()=>{const s=createGame();act(s,'prepare',0);act(s,'accept','P0');act(s,'talk','P0');act(s,'fulfill','P0');act(s,'assign','P0','F5');assert.equal(s.credits,0);assert.equal(s.reputation,10);while(s.time<5)act(s,'wait');assert(s.credits>=10&&s.credits<=20);const c=s.credits;act(s,'wait');assert.equal(s.credits,c);});
test('Credits and random state persist across reload and shifts',()=>{const s=departure('pet');const copy=restoreGame(JSON.parse(JSON.stringify(s)));assert.equal(copy.credits,s.credits);assert.equal(copy.rng,s.rng);s.tick=29;s.time=29;act(s,'wait');const c=s.credits;nextShift(s);assert.equal(s.credits,c);assert.equal(s.resource,45);});
test('Old save gets credits and economy without losing resource or passengers',()=>{const s=createGame();s.version=2;delete s.credits;delete s.rng;for(const key of Object.keys(ECONOMY))delete s.config[key];s.resource=19;s.reputation=37;const upgraded=restoreGame(s);assert.equal(upgraded.credits,0);assert.equal(upgraded.resource,19);assert.equal(upgraded.reputation,37);assert.equal(upgraded.config.prepareCost,2);assert.deepEqual(upgraded.queue,s.queue);});
test('Balance overrides affect actual rewards, costs, limits and penalties',()=>{const s=departure('contraband','allow',{contrabandMin:40,contrabandMax:40,contrabandPenaltyMin:7,contrabandPenaltyMax:7});assert.equal(s.credits,40);assert.equal(s.reputation,3);const x=createGame({startCredits:100,prepareCost:5,refillRate:4,refillMax:2});act(x,'prepare',0);assert.equal(x.resource,40);assert(!act(x,'refill',3).ok);act(x,'refill',2);assert.equal(x.resource,42);assert.equal(x.credits,92);assert.equal(x.tick,0);});
test('Queue departure remains minus three without credit reward',()=>{const s=createGame();s.queue[0].patience=1;act(s,'wait');assert.equal(s.credits,0);assert.equal(s.reputation,7);});
console.log(tests+' credit checks passed.');
