import assert from 'node:assert/strict';
import {createGame,act,reason,nextShift,consumption,seats,validSave} from './engine.mjs';
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function ready(s){s.rooms.forEach(r=>act(s,'prepare',r.id));}
function accept(s,id){assert.equal(act(s,'accept',id).ok,true);}
function talk(s,id){assert.equal(act(s,'talk',id).ok,true);}
test('Spec defaults, three room types and no old economy',()=>{const s=createGame();assert.equal(s.config.ticks,30);assert.equal(s.resource,45);assert.deepEqual(s.rooms.map(r=>r.type),['dry','dry','water']);assert.equal(s.credits,undefined);assert(validSave(s));});
test('Cannot accept into unprepared room; blocked actions are no-ops',()=>{const s=createGame(),before=JSON.stringify(s);assert(!act(s,'accept','P0').ok);assert.equal(JSON.stringify(s),before);});
test('Preparation is free and repeat preparation a true no-op',()=>{const s=createGame();act(s,'prepare',0);assert.equal(s.tick,0);const before=JSON.stringify(s);assert(!act(s,'prepare',0).ok);assert.equal(JSON.stringify(s),before);});
test('Acceptance consumes one tick and one unit for the new passenger',()=>{const s=createGame();ready(s);accept(s,'P0');assert.equal(s.tick,1);assert.equal(s.resource,44);assert.equal(s.rooms[0].p.id,'P0');});
test('Water passenger uses only water room',()=>{const s=createGame();act(s,'prepare',0);assert(!act(s,'accept','P1').ok);act(s,'prepare',2);accept(s,'P1');assert.equal(s.rooms[2].p.id,'P1');});
test('Conversation and condition free; requirement gates booking',()=>{const s=createGame();ready(s);accept(s,'P0');assert(!act(s,'assign','P0','F5').ok);talk(s,'P0');assert.equal(s.tick,1);assert(!act(s,'assign','P0','F5').ok);act(s,'fulfill','P0');assert.equal(s.tick,1);assert.equal(s.resource,44);assert.equal(seats(s.rooms[0].p),2);});
test('Booking reserves seats but keeps room until scheduled departure',()=>{const s=createGame();ready(s);accept(s,'P0');talk(s,'P0');act(s,'fulfill','P0');act(s,'assign','P0','F5');assert.equal(s.time,2);assert.equal(s.rooms[0].p.flight,'F5');assert.equal(s.flights[0].used,2);assert.equal(s.stats.departed,0);const before=JSON.stringify(s);assert(!act(s,'assign','P0','F5').ok);assert.equal(JSON.stringify(s),before);while(s.time<5)act(s,'wait');assert.equal(s.stats.departed,1);assert.equal(s.rooms[0].p,null);assert.equal(s.rooms[0].prepared,false);assert.equal(s.resource,40);});
test('Several passengers share a flight and depart together',()=>{const s=createGame();ready(s);accept(s,'P0');talk(s,'P0');act(s,'fulfill','P0');act(s,'assign','P0','F5');accept(s,'P2');talk(s,'P2');act(s,'assign','P2','F5');assert.equal(s.flights[0].used,3);assert.equal(s.rooms.filter(r=>r.p).length,2);act(s,'wait');assert.equal(s.stats.departed,2);assert.equal(consumption(s),0);});
test('Last-tick booking succeeds before automatic departure',()=>{const s=createGame();ready(s);accept(s,'P2');talk(s,'P2');while(s.time<4)act(s,'wait');assert(act(s,'assign','P2','F5').ok);assert.equal(s.stats.departed,1);});
test('Capacity includes pet and prevents overbooking',()=>{const s=createGame();ready(s);accept(s,'P0');talk(s,'P0');act(s,'fulfill','P0');s.flights[0].capacity=1;const before=JSON.stringify(s);assert.match(reason(s,'assign','P0','F5'),/Нужно 2/);assert(!act(s,'assign','P0','F5').ok);assert.equal(JSON.stringify(s),before);});
test('Wrong destination is blocked',()=>{const s=createGame();ready(s);accept(s,'P2');talk(s,'P2');assert.match(reason(s,'assign','P2','F7'),/Другое/);});
test('Missed flight leaves unbooked passenger in room, consuming resource',()=>{const s=createGame();ready(s);accept(s,'P2');while(s.time<6)act(s,'wait');assert.equal(s.rooms[0].p.id,'P2');assert.equal(s.resource,39);assert(s.flights.some(f=>f.dest==='Марс'));});
test('Empty flights still depart and waiting is explicit',()=>{const s=createGame();while(s.time<5)act(s,'wait');assert.equal(s.stats.flights,1);assert.equal(s.stats.departed,0);assert.equal(s.resource,45);});
test('Queue patience and periodic arrivals',()=>{const s=createGame();for(let i=0;i<3;i++)act(s,'wait');assert.equal(s.queue.length,4);assert.equal(s.queue[0].patience,6);while(s.time<9)act(s,'wait');assert(!s.queue.some(p=>p.id==='P0'));assert(s.stats.left>0);});
test('Group consumes two resource units and needs two seats',()=>{const s=createGame();ready(s);while(s.time<6)act(s,'wait');accept(s,'P4');assert.equal(consumption(s),2);assert.equal(s.resource,43);assert.equal(seats(s.rooms[2].p),2);});
test('Contraband supports both explicit choices without money',()=>{for(const choice of ['allow','seize']){const s=createGame();ready(s);while(s.time<9)act(s,'wait');accept(s,'P5');talk(s,'P5');const t=s.tick;act(s,'fulfill','P5',choice);assert.equal(s.rooms[0].p.decision,choice);assert.equal(s.tick,t);}});
test('Exactly 30 ticks end shift; no accidental 31st tick',()=>{const s=createGame();for(let i=0;i<30;i++)act(s,'wait');assert(s.ended);assert.equal(s.tick,30);const b=JSON.stringify(s);assert(!act(s,'wait').ok);assert.equal(JSON.stringify(s),b);});
test('New shift restores resource and preserves residents and reservations',()=>{const s=createGame({resource:100});ready(s);while(s.time<27)act(s,'wait');const p=s.queue.find(p=>p.type==='dry');accept(s,p.id);talk(s,p.id);if(p.condition)act(s,'fulfill',p.id);const f=s.flights.find(f=>f.dest===p.dest&&f.at>30);act(s,'assign',p.id,f.id);act(s,'wait');assert(s.ended);const r=s.rooms.find(r=>r.p);nextShift(s);assert.equal(s.resource,100);assert.equal(s.tick,0);assert.equal(r.p.flight,f.id);while(s.time<f.at)act(s,'wait');assert.equal(r.p,null);});
test('Exhaustion freezes attempt without making passengers disappear',()=>{const s=createGame({resource:2});ready(s);accept(s,'P2');act(s,'wait');assert(s.failed);assert.equal(s.rooms[0].p.id,'P2');assert.equal(s.resource,0);assert(!act(s,'wait').ok);assert(!nextShift(s));});
test('Long play has unique, repeating flight schedule across shifts',()=>{const s=createGame();for(let i=0;i<20;i++){for(let t=0;t<30;t++)act(s,'wait');assert(s.ended);assert.equal(new Set(s.flights.map(f=>f.id)).size,s.flights.length);assert(s.flights.every(f=>f.at>s.time));assert(nextShift(s));}assert.equal(s.time,600);assert.equal(s.stats.flights,199);});
test('Configurable room counts',()=>{const s=createGame({rooms:['water','water','dry','dry','dry']});assert.equal(s.rooms.length,5);ready(s);assert(s.rooms.every(r=>r.prepared));});
test('Seeded action fuzz: capacity, resource, room identity and time invariants',()=>{let seed=13;const rand=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);for(let run=0;run<100;run++){const s=createGame({resource:150});for(let k=0;k<180;k++){if(s.ended){nextShift(s);continue;}if(s.failed)break;ready(s);const people=[...s.queue,...s.rooms.flatMap(r=>r.p?[r.p]:[])],p=people[Math.floor(rand()*people.length)];const action=['accept','talk','fulfill','assign','wait'][Math.floor(rand()*5)];act(s,action,p?.id,s.flights[Math.floor(rand()*Math.min(6,s.flights.length))].id);assert(s.resource>=0);assert(s.tick<=s.config.ticks);assert(s.flights.every(f=>f.used<=f.capacity));const ids=s.rooms.flatMap(r=>r.p?[r.p.id]:[]);assert.equal(ids.length,new Set(ids).size);for(const r of s.rooms){if(r.p)assert.equal(r.p.type,r.type);}for(const f of s.flights)assert.equal(f.used,s.rooms.reduce((n,r)=>n+(r.p?.flight===f.id?seats(r.p):0),0));}}});
console.log(`\n${passed} tests passed.`);

