import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);let pw;try{pw=require('playwright');}catch{pw=require('C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}const {chromium}=pw;
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.clock.install();await page.goto(process.env.TEST_URL||'http://127.0.0.1:4173');
const action=(name)=>page.locator(`[data-action="${name}"]`);const nav=name=>page.getByRole('button',{name,exact:true}).click();
for(let batch of [1,2,2]){for(let i=0;i<batch;i++){await action('admitDialog').first().click();await action('confirmFuel').click();await action('assignDialog').nth(i).click();await action('assignClose').first().click();}await action('launch').first().click();if(batch===1)await page.locator('.top-controls [data-action="pause"]').click();await page.clock.fastForward((10+8*batch+1)*1000);}
await action('factoryOpen').click();let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('quiet-orbit-v1')));assert.equal(state.tutorial.done,true);assert.equal(state.credits,500);assert.equal(state.rep,35);assert.deepEqual(state.stock,[35,15,15,15]);assert.equal(state.cells,20);console.log('PASS UI tutorial exact economy');
await nav('Фабрика');await page.locator('[aria-label="Ячейка 7: Пусто"]').click();await action('chooseMachine').nth(1).click();await page.locator('[aria-label="Ячейка 8: Пусто"]').click();await action('chooseMachine').nth(2).click();await page.locator('[aria-label="Ячейка 9: Пусто"]').click();state=await page.evaluate(()=>JSON.parse(localStorage.getItem('quiet-orbit-v1')));assert.equal(state.paused,true);assert.equal(state.grid.filter(x=>x&&x.type<4).length,3);await page.screenshot({path:'tests/factory.png',fullPage:true});console.log('PASS UI factory placement and auto pause');
await nav('Контракты');await action('selectQuest').first().click();await action('accept').click();assert.equal(await action('selectQuest').count(),2);console.log('PASS UI contract acceptance');
await nav('Станция');await action('admitDialog').first().click();await action('quantity').filter({hasText:'Max'}).click();await page.screenshot({path:'tests/passenger.png'});await action('close').click();
for(let width of [1440,1024,768,390,375]){await page.setViewportSize({width,height:1000});for(let name of ['Станция','Контракты','Фабрика','Развитие','Склад','Журнал','Испытания']){await nav(name);let overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`overflow ${width} ${name}`);}await nav('Станция');if(width===1440||width===390)await page.screenshot({path:`tests/${width===1440?'desktop':'mobile'}.png`,fullPage:true});}
assert.deepEqual(errors,[]);console.log('PASS 35 responsive screen checks; zero browser errors');await browser.close();
